"""empty message

Revision ID: 4150b2341df2
Revises: 769aab71ed1a
Create Date: 2019-12-17 12:09:04.554930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4150b2341df2'
down_revision = '769aab71ed1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cancer_history', sa.Column('prediction', sa.Integer(), nullable=True))
    op.add_column('diabetes_history', sa.Column('prediction', sa.Integer(), nullable=True))
    op.add_column('heart_disease_history', sa.Column('prediction', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('heart_disease_history', 'prediction')
    op.drop_column('diabetes_history', 'prediction')
    op.drop_column('cancer_history', 'prediction')
    # ### end Alembic commands ###
