"""empty message

Revision ID: ee2f9dd279f1
Revises: 18113f6eb96d
Create Date: 2019-12-01 22:42:21.372107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee2f9dd279f1'
down_revision = '18113f6eb96d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cancer_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('glucose', sa.Float(), nullable=True),
    sa.Column('insulin', sa.Float(), nullable=True),
    sa.Column('homa', sa.Integer(), nullable=True),
    sa.Column('leptin', sa.Float(), nullable=True),
    sa.Column('adiponectin', sa.Integer(), nullable=True),
    sa.Column('resistin', sa.Integer(), nullable=True),
    sa.Column('mcp_1', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('heart_disease_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.Integer(), nullable=True),
    sa.Column('chest_pain_type', sa.Integer(), nullable=True),
    sa.Column('resting_blood_pressure', sa.Integer(), nullable=True),
    sa.Column('cholesterol', sa.Integer(), nullable=True),
    sa.Column('fasting_blood_sugar', sa.Float(), nullable=True),
    sa.Column('resting_electrocardiographic', sa.Float(), nullable=True),
    sa.Column('maximum_heart_rate', sa.Integer(), nullable=True),
    sa.Column('exercise_induced_angina', sa.Integer(), nullable=True),
    sa.Column('epression_induced_exercise', sa.Integer(), nullable=True),
    sa.Column('peak_exercise', sa.Integer(), nullable=True),
    sa.Column('number_major_vessels', sa.Integer(), nullable=True),
    sa.Column('thal', sa.Integer(), nullable=True),
    sa.Column('diagnosis_heart_disease', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('diabetes_history', 'class_variable')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diabetes_history', sa.Column('class_variable', sa.INTEGER(), nullable=True))
    op.drop_table('heart_disease_history')
    op.drop_table('cancer_history')
    # ### end Alembic commands ###
